/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lightState.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lightState.pb-c.h"
void   bot_code__light_state__agent_state__init
                     (BotCode__LightState__AgentState         *message)
{
  static const BotCode__LightState__AgentState init_value = BOT_CODE__LIGHT_STATE__AGENT_STATE__INIT;
  *message = init_value;
}
void   bot_code__light_state__init
                     (BotCode__LightState         *message)
{
  static const BotCode__LightState init_value = BOT_CODE__LIGHT_STATE__INIT;
  *message = init_value;
}
size_t bot_code__light_state__get_packed_size
                     (const BotCode__LightState *message)
{
  assert(message->base.descriptor == &bot_code__light_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot_code__light_state__pack
                     (const BotCode__LightState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot_code__light_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot_code__light_state__pack_to_buffer
                     (const BotCode__LightState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot_code__light_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotCode__LightState *
       bot_code__light_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotCode__LightState *)
     protobuf_c_message_unpack (&bot_code__light_state__descriptor,
                                allocator, len, data);
}
void   bot_code__light_state__free_unpacked
                     (BotCode__LightState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot_code__light_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bot_code__light_state__agent_state__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState__AgentState, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState__AgentState, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(BotCode__LightState__AgentState, has_state),
    offsetof(BotCode__LightState__AgentState, state),
    &bot_code__light_state__ghost_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot_code__light_state__agent_state__field_indices_by_name[] = {
  2,   /* field[2] = state */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange bot_code__light_state__agent_state__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bot_code__light_state__agent_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "botCode.LightState.AgentState",
  "AgentState",
  "BotCode__LightState__AgentState",
  "botCode",
  sizeof(BotCode__LightState__AgentState),
  3,
  bot_code__light_state__agent_state__field_descriptors,
  bot_code__light_state__agent_state__field_indices_by_name,
  2,  bot_code__light_state__agent_state__number_ranges,
  (ProtobufCMessageInit) bot_code__light_state__agent_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue bot_code__light_state__game_mode__enum_values_by_number[2] =
{
  { "RUNNING", "BOT_CODE__LIGHT_STATE__GAME_MODE__RUNNING", 0 },
  { "PAUSED", "BOT_CODE__LIGHT_STATE__GAME_MODE__PAUSED", 1 },
};
static const ProtobufCIntRange bot_code__light_state__game_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex bot_code__light_state__game_mode__enum_values_by_name[2] =
{
  { "PAUSED", 1 },
  { "RUNNING", 0 },
};
const ProtobufCEnumDescriptor bot_code__light_state__game_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "botCode.LightState.GameMode",
  "GameMode",
  "BotCode__LightState__GameMode",
  "botCode",
  2,
  bot_code__light_state__game_mode__enum_values_by_number,
  2,
  bot_code__light_state__game_mode__enum_values_by_name,
  1,
  bot_code__light_state__game_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue bot_code__light_state__ghost_state__enum_values_by_number[2] =
{
  { "NORMAL", "BOT_CODE__LIGHT_STATE__GHOST_STATE__NORMAL", 0 },
  { "FRIGHTENED", "BOT_CODE__LIGHT_STATE__GHOST_STATE__FRIGHTENED", 1 },
};
static const ProtobufCIntRange bot_code__light_state__ghost_state__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex bot_code__light_state__ghost_state__enum_values_by_name[2] =
{
  { "FRIGHTENED", 1 },
  { "NORMAL", 0 },
};
const ProtobufCEnumDescriptor bot_code__light_state__ghost_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "botCode.LightState.GhostState",
  "GhostState",
  "BotCode__LightState__GhostState",
  "botCode",
  2,
  bot_code__light_state__ghost_state__enum_values_by_number,
  2,
  bot_code__light_state__ghost_state__enum_values_by_name,
  1,
  bot_code__light_state__ghost_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor bot_code__light_state__field_descriptors[8] =
{
  {
    "pacman",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, pacman),
    &bot_code__light_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red_ghost",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, red_ghost),
    &bot_code__light_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pink_ghost",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, pink_ghost),
    &bot_code__light_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orange_ghost",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, orange_ghost),
    &bot_code__light_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue_ghost",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, blue_ghost),
    &bot_code__light_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, mode),
    &bot_code__light_state__game_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lives",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__LightState, lives),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot_code__light_state__field_indices_by_name[] = {
  4,   /* field[4] = blue_ghost */
  7,   /* field[7] = lives */
  5,   /* field[5] = mode */
  3,   /* field[3] = orange_ghost */
  0,   /* field[0] = pacman */
  2,   /* field[2] = pink_ghost */
  1,   /* field[1] = red_ghost */
  6,   /* field[6] = score */
};
static const ProtobufCIntRange bot_code__light_state__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 8, 6 },
  { 11, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor bot_code__light_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "botCode.LightState",
  "LightState",
  "BotCode__LightState",
  "botCode",
  sizeof(BotCode__LightState),
  8,
  bot_code__light_state__field_descriptors,
  bot_code__light_state__field_indices_by_name,
  3,  bot_code__light_state__number_ranges,
  (ProtobufCMessageInit) bot_code__light_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
