/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lightState.proto */

#ifndef PROTOBUF_C_lightState_2eproto__INCLUDED
#define PROTOBUF_C_lightState_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _BotCode__LightState BotCode__LightState;
typedef struct _BotCode__LightState__AgentState BotCode__LightState__AgentState;


/* --- enums --- */

typedef enum _BotCode__LightState__GameMode {
  BOT_CODE__LIGHT_STATE__GAME_MODE__RUNNING = 0,
  BOT_CODE__LIGHT_STATE__GAME_MODE__PAUSED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BOT_CODE__LIGHT_STATE__GAME_MODE)
} BotCode__LightState__GameMode;
typedef enum _BotCode__LightState__GhostState {
  BOT_CODE__LIGHT_STATE__GHOST_STATE__NORMAL = 0,
  BOT_CODE__LIGHT_STATE__GHOST_STATE__FRIGHTENED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BOT_CODE__LIGHT_STATE__GHOST_STATE)
} BotCode__LightState__GhostState;

/* --- messages --- */

struct  _BotCode__LightState__AgentState
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
  protobuf_c_boolean has_state;
  BotCode__LightState__GhostState state;
};
#define BOT_CODE__LIGHT_STATE__AGENT_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bot_code__light_state__agent_state__descriptor) \
    , 0, 0, 0, BOT_CODE__LIGHT_STATE__GHOST_STATE__NORMAL }


struct  _BotCode__LightState
{
  ProtobufCMessage base;
  BotCode__LightState__AgentState *pacman;
  BotCode__LightState__AgentState *red_ghost;
  BotCode__LightState__AgentState *pink_ghost;
  BotCode__LightState__AgentState *orange_ghost;
  BotCode__LightState__AgentState *blue_ghost;
  BotCode__LightState__GameMode mode;
  int32_t score;
  int32_t lives;
};
#define BOT_CODE__LIGHT_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bot_code__light_state__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, BOT_CODE__LIGHT_STATE__GAME_MODE__RUNNING, 0, 0 }


/* BotCode__LightState__AgentState methods */
void   bot_code__light_state__agent_state__init
                     (BotCode__LightState__AgentState         *message);
/* BotCode__LightState methods */
void   bot_code__light_state__init
                     (BotCode__LightState         *message);
size_t bot_code__light_state__get_packed_size
                     (const BotCode__LightState   *message);
size_t bot_code__light_state__pack
                     (const BotCode__LightState   *message,
                      uint8_t             *out);
size_t bot_code__light_state__pack_to_buffer
                     (const BotCode__LightState   *message,
                      ProtobufCBuffer     *buffer);
BotCode__LightState *
       bot_code__light_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bot_code__light_state__free_unpacked
                     (BotCode__LightState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BotCode__LightState__AgentState_Closure)
                 (const BotCode__LightState__AgentState *message,
                  void *closure_data);
typedef void (*BotCode__LightState_Closure)
                 (const BotCode__LightState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bot_code__light_state__descriptor;
extern const ProtobufCMessageDescriptor bot_code__light_state__agent_state__descriptor;
extern const ProtobufCEnumDescriptor    bot_code__light_state__game_mode__descriptor;
extern const ProtobufCEnumDescriptor    bot_code__light_state__ghost_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_lightState_2eproto__INCLUDED */
