/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pacmanCommand.proto */

#ifndef PROTOBUF_C_pacmanCommand_2eproto__INCLUDED
#define PROTOBUF_C_pacmanCommand_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _BotCode__PacmanCommand BotCode__PacmanCommand;


/* --- enums --- */

typedef enum _BotCode__PacmanCommand__Direction {
  BOT_CODE__PACMAN_COMMAND__DIRECTION__STOP = 1,
  BOT_CODE__PACMAN_COMMAND__DIRECTION__NORTH = 2,
  BOT_CODE__PACMAN_COMMAND__DIRECTION__SOUTH = 3,
  BOT_CODE__PACMAN_COMMAND__DIRECTION__EAST = 4,
  BOT_CODE__PACMAN_COMMAND__DIRECTION__WEST = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BOT_CODE__PACMAN_COMMAND__DIRECTION)
} BotCode__PacmanCommand__Direction;

/* --- messages --- */

struct  _BotCode__PacmanCommand
{
  ProtobufCMessage base;
  BotCode__PacmanCommand__Direction dir;
};
#define BOT_CODE__PACMAN_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bot_code__pacman_command__descriptor) \
    , BOT_CODE__PACMAN_COMMAND__DIRECTION__STOP }


/* BotCode__PacmanCommand methods */
void   bot_code__pacman_command__init
                     (BotCode__PacmanCommand         *message);
size_t bot_code__pacman_command__get_packed_size
                     (const BotCode__PacmanCommand   *message);
size_t bot_code__pacman_command__pack
                     (const BotCode__PacmanCommand   *message,
                      uint8_t             *out);
size_t bot_code__pacman_command__pack_to_buffer
                     (const BotCode__PacmanCommand   *message,
                      ProtobufCBuffer     *buffer);
BotCode__PacmanCommand *
       bot_code__pacman_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bot_code__pacman_command__free_unpacked
                     (BotCode__PacmanCommand *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BotCode__PacmanCommand_Closure)
                 (const BotCode__PacmanCommand *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bot_code__pacman_command__descriptor;
extern const ProtobufCEnumDescriptor    bot_code__pacman_command__direction__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pacmanCommand_2eproto__INCLUDED */
