/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pacmanCommand.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pacmanCommand.pb-c.h"
void   bot_code__pacman_command__init
                     (BotCode__PacmanCommand         *message)
{
  static const BotCode__PacmanCommand init_value = BOT_CODE__PACMAN_COMMAND__INIT;
  *message = init_value;
}
size_t bot_code__pacman_command__get_packed_size
                     (const BotCode__PacmanCommand *message)
{
  assert(message->base.descriptor == &bot_code__pacman_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot_code__pacman_command__pack
                     (const BotCode__PacmanCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot_code__pacman_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot_code__pacman_command__pack_to_buffer
                     (const BotCode__PacmanCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot_code__pacman_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotCode__PacmanCommand *
       bot_code__pacman_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotCode__PacmanCommand *)
     protobuf_c_message_unpack (&bot_code__pacman_command__descriptor,
                                allocator, len, data);
}
void   bot_code__pacman_command__free_unpacked
                     (BotCode__PacmanCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot_code__pacman_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue bot_code__pacman_command__direction__enum_values_by_number[5] =
{
  { "STOP", "BOT_CODE__PACMAN_COMMAND__DIRECTION__STOP", 1 },
  { "NORTH", "BOT_CODE__PACMAN_COMMAND__DIRECTION__NORTH", 2 },
  { "SOUTH", "BOT_CODE__PACMAN_COMMAND__DIRECTION__SOUTH", 3 },
  { "EAST", "BOT_CODE__PACMAN_COMMAND__DIRECTION__EAST", 4 },
  { "WEST", "BOT_CODE__PACMAN_COMMAND__DIRECTION__WEST", 5 },
};
static const ProtobufCIntRange bot_code__pacman_command__direction__value_ranges[] = {
{1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex bot_code__pacman_command__direction__enum_values_by_name[5] =
{
  { "EAST", 3 },
  { "NORTH", 1 },
  { "SOUTH", 2 },
  { "STOP", 0 },
  { "WEST", 4 },
};
const ProtobufCEnumDescriptor bot_code__pacman_command__direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "botCode.PacmanCommand.Direction",
  "Direction",
  "BotCode__PacmanCommand__Direction",
  "botCode",
  5,
  bot_code__pacman_command__direction__enum_values_by_number,
  5,
  bot_code__pacman_command__direction__enum_values_by_name,
  1,
  bot_code__pacman_command__direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor bot_code__pacman_command__field_descriptors[1] =
{
  {
    "dir",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanCommand, dir),
    &bot_code__pacman_command__direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot_code__pacman_command__field_indices_by_name[] = {
  0,   /* field[0] = dir */
};
static const ProtobufCIntRange bot_code__pacman_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bot_code__pacman_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "botCode.PacmanCommand",
  "PacmanCommand",
  "BotCode__PacmanCommand",
  "botCode",
  sizeof(BotCode__PacmanCommand),
  1,
  bot_code__pacman_command__field_descriptors,
  bot_code__pacman_command__field_indices_by_name,
  1,  bot_code__pacman_command__number_ranges,
  (ProtobufCMessageInit) bot_code__pacman_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
