/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pacmanState.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pacmanState.pb-c.h"
void   bot_code__pacman_state__agent_state__init
                     (BotCode__PacmanState__AgentState         *message)
{
  static const BotCode__PacmanState__AgentState init_value = BOT_CODE__PACMAN_STATE__AGENT_STATE__INIT;
  *message = init_value;
}
void   bot_code__pacman_state__init
                     (BotCode__PacmanState         *message)
{
  static const BotCode__PacmanState init_value = BOT_CODE__PACMAN_STATE__INIT;
  *message = init_value;
}
size_t bot_code__pacman_state__get_packed_size
                     (const BotCode__PacmanState *message)
{
  assert(message->base.descriptor == &bot_code__pacman_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot_code__pacman_state__pack
                     (const BotCode__PacmanState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot_code__pacman_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot_code__pacman_state__pack_to_buffer
                     (const BotCode__PacmanState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot_code__pacman_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotCode__PacmanState *
       bot_code__pacman_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotCode__PacmanState *)
     protobuf_c_message_unpack (&bot_code__pacman_state__descriptor,
                                allocator, len, data);
}
void   bot_code__pacman_state__free_unpacked
                     (BotCode__PacmanState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot_code__pacman_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bot_code__pacman_state__agent_state__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState__AgentState, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState__AgentState, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(BotCode__PacmanState__AgentState, has_direction),
    offsetof(BotCode__PacmanState__AgentState, direction),
    &bot_code__pacman_state__direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frightened_counter",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(BotCode__PacmanState__AgentState, has_frightened_counter),
    offsetof(BotCode__PacmanState__AgentState, frightened_counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot_code__pacman_state__agent_state__field_indices_by_name[] = {
  2,   /* field[2] = direction */
  3,   /* field[3] = frightened_counter */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange bot_code__pacman_state__agent_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor bot_code__pacman_state__agent_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "botCode.PacmanState.AgentState",
  "AgentState",
  "BotCode__PacmanState__AgentState",
  "botCode",
  sizeof(BotCode__PacmanState__AgentState),
  4,
  bot_code__pacman_state__agent_state__field_descriptors,
  bot_code__pacman_state__agent_state__field_indices_by_name,
  1,  bot_code__pacman_state__agent_state__number_ranges,
  (ProtobufCMessageInit) bot_code__pacman_state__agent_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue bot_code__pacman_state__game_mode__enum_values_by_number[4] =
{
  { "CHASE", "BOT_CODE__PACMAN_STATE__GAME_MODE__CHASE", 0 },
  { "SCATTER", "BOT_CODE__PACMAN_STATE__GAME_MODE__SCATTER", 1 },
  { "FRIGHTENED", "BOT_CODE__PACMAN_STATE__GAME_MODE__FRIGHTENED", 2 },
  { "PAUSED", "BOT_CODE__PACMAN_STATE__GAME_MODE__PAUSED", 3 },
};
static const ProtobufCIntRange bot_code__pacman_state__game_mode__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex bot_code__pacman_state__game_mode__enum_values_by_name[4] =
{
  { "CHASE", 0 },
  { "FRIGHTENED", 2 },
  { "PAUSED", 3 },
  { "SCATTER", 1 },
};
const ProtobufCEnumDescriptor bot_code__pacman_state__game_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "botCode.PacmanState.GameMode",
  "GameMode",
  "BotCode__PacmanState__GameMode",
  "botCode",
  4,
  bot_code__pacman_state__game_mode__enum_values_by_number,
  4,
  bot_code__pacman_state__game_mode__enum_values_by_name,
  1,
  bot_code__pacman_state__game_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue bot_code__pacman_state__grid_element__enum_values_by_number[4] =
{
  { "WALL", "BOT_CODE__PACMAN_STATE__GRID_ELEMENT__WALL", 0 },
  { "PELLET", "BOT_CODE__PACMAN_STATE__GRID_ELEMENT__PELLET", 1 },
  { "POWER_PELLET", "BOT_CODE__PACMAN_STATE__GRID_ELEMENT__POWER_PELLET", 2 },
  { "EMPTY", "BOT_CODE__PACMAN_STATE__GRID_ELEMENT__EMPTY", 3 },
};
static const ProtobufCIntRange bot_code__pacman_state__grid_element__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex bot_code__pacman_state__grid_element__enum_values_by_name[4] =
{
  { "EMPTY", 3 },
  { "PELLET", 1 },
  { "POWER_PELLET", 2 },
  { "WALL", 0 },
};
const ProtobufCEnumDescriptor bot_code__pacman_state__grid_element__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "botCode.PacmanState.GridElement",
  "GridElement",
  "BotCode__PacmanState__GridElement",
  "botCode",
  4,
  bot_code__pacman_state__grid_element__enum_values_by_number,
  4,
  bot_code__pacman_state__grid_element__enum_values_by_name,
  1,
  bot_code__pacman_state__grid_element__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue bot_code__pacman_state__direction__enum_values_by_number[4] =
{
  { "UP", "BOT_CODE__PACMAN_STATE__DIRECTION__UP", 0 },
  { "DOWN", "BOT_CODE__PACMAN_STATE__DIRECTION__DOWN", 1 },
  { "LEFT", "BOT_CODE__PACMAN_STATE__DIRECTION__LEFT", 2 },
  { "RIGHT", "BOT_CODE__PACMAN_STATE__DIRECTION__RIGHT", 3 },
};
static const ProtobufCIntRange bot_code__pacman_state__direction__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex bot_code__pacman_state__direction__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor bot_code__pacman_state__direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "botCode.PacmanState.Direction",
  "Direction",
  "BotCode__PacmanState__Direction",
  "botCode",
  4,
  bot_code__pacman_state__direction__enum_values_by_number,
  4,
  bot_code__pacman_state__direction__enum_values_by_name,
  1,
  bot_code__pacman_state__direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor bot_code__pacman_state__field_descriptors[14] =
{
  {
    "pacman",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, pacman),
    &bot_code__pacman_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red_ghost",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, red_ghost),
    &bot_code__pacman_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pink_ghost",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, pink_ghost),
    &bot_code__pacman_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orange_ghost",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, orange_ghost),
    &bot_code__pacman_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue_ghost",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, blue_ghost),
    &bot_code__pacman_state__agent_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, mode),
    &bot_code__pacman_state__game_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frightened_timer",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, frightened_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grid",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(BotCode__PacmanState, n_grid),
    offsetof(BotCode__PacmanState, grid),
    &bot_code__pacman_state__grid_element__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grid_columns",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, grid_columns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lives",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, lives),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_ticks",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, update_ticks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ticks_per_update",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BotCode__PacmanState, ticks_per_update),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elapsed_time",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(BotCode__PacmanState, has_elapsed_time),
    offsetof(BotCode__PacmanState, elapsed_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot_code__pacman_state__field_indices_by_name[] = {
  4,   /* field[4] = blue_ghost */
  13,   /* field[13] = elapsed_time */
  6,   /* field[6] = frightened_timer */
  8,   /* field[8] = grid */
  9,   /* field[9] = grid_columns */
  10,   /* field[10] = lives */
  5,   /* field[5] = mode */
  3,   /* field[3] = orange_ghost */
  0,   /* field[0] = pacman */
  2,   /* field[2] = pink_ghost */
  1,   /* field[1] = red_ghost */
  7,   /* field[7] = score */
  12,   /* field[12] = ticks_per_update */
  11,   /* field[11] = update_ticks */
};
static const ProtobufCIntRange bot_code__pacman_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor bot_code__pacman_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "botCode.PacmanState",
  "PacmanState",
  "BotCode__PacmanState",
  "botCode",
  sizeof(BotCode__PacmanState),
  14,
  bot_code__pacman_state__field_descriptors,
  bot_code__pacman_state__field_indices_by_name,
  1,  bot_code__pacman_state__number_ranges,
  (ProtobufCMessageInit) bot_code__pacman_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
