protobuf: lightState.proto pacmanState.proto pacmanCommand.proto
	protoc -I=./ --python_out=./ ./lightState.proto
	protoc -I=./ --python_out=./ ./pacmanState.proto
	protoc -I=./ --python_out=./ ./pacmanCommand.proto
