# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pacmanCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pacmanCommand.proto',
  package='botCode',
  syntax='proto2',
  serialized_pb=_b('\n\x13pacmanCommand.proto\x12\x07\x62otCode\"\x7f\n\rPacmanCommand\x12-\n\x03\x64ir\x18\x01 \x02(\x0e\x32 .botCode.PacmanCommand.Direction\"?\n\tDirection\x12\x08\n\x04STOP\x10\x01\x12\t\n\x05NORTH\x10\x02\x12\t\n\x05SOUTH\x10\x03\x12\x08\n\x04\x45\x41ST\x10\x04\x12\x08\n\x04WEST\x10\x05')
)



_PACMANCOMMAND_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='botCode.PacmanCommand.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORTH', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOUTH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EAST', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEST', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=96,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_PACMANCOMMAND_DIRECTION)


_PACMANCOMMAND = _descriptor.Descriptor(
  name='PacmanCommand',
  full_name='botCode.PacmanCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='botCode.PacmanCommand.dir', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PACMANCOMMAND_DIRECTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=159,
)

_PACMANCOMMAND.fields_by_name['dir'].enum_type = _PACMANCOMMAND_DIRECTION
_PACMANCOMMAND_DIRECTION.containing_type = _PACMANCOMMAND
DESCRIPTOR.message_types_by_name['PacmanCommand'] = _PACMANCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacmanCommand = _reflection.GeneratedProtocolMessageType('PacmanCommand', (_message.Message,), dict(
  DESCRIPTOR = _PACMANCOMMAND,
  __module__ = 'pacmanCommand_pb2'
  # @@protoc_insertion_point(class_scope:botCode.PacmanCommand)
  ))
_sym_db.RegisterMessage(PacmanCommand)


# @@protoc_insertion_point(module_scope)
